service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
plugins:
  - serverless-plugin-typescript
resources:
  Resources:
    moneyTrackerWallets:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: money-tracker-wallets
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: walletId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: walletId
            KeyType: HASH
    moneyTrackerExpenses:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: money-tracker-expenses
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: walletId
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: walletId
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE